name: Add issue or PR to project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Add to GitHub Project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/arielswalker/projects/2
        env:
          GH_TOKEN: ${{ secrets.ADD_TO_PROJECT }}
