name: Trigger Webhook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook.yml
        run: |
          curl -v -X POST \
          -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" \
          -H "Accept: application/vnd.github.v3+json" \
          ${{ secrets.WEBHOOK_URL }} \
          -d '{"ref": "main"}'
