name: Test Webhook

on:
  repository_dispatch:
    types: [issues]  # The event_type you want to trigger the workflow with

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Test"
